version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-builder
    volumes:
      - ./server:/app
    command: poetry run python server.py
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-builder
    volumes:
      - ./frontend:/app
    command: yarn start
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
